### ISSUE TITLE
Consider renaming this repo and the published package to 'cli-build-app'

### ISSUE THREAD

**Issue by rishson** [dojo/cli-build-webpack#109]
It has been the source of some confusion that the repo is called `cli-build` but the package is called `cli-build-webpack`.

I think we should isolate ourselves from a specific implementation (in this case `webpack`) and rename the repo to `cli-build-app` and use this name for the published package.

**Comment by mwistrand** [comment]
When you say, "build widgets", do you mean generate a new widget? If that is the case, then I would implement that via a `dojo create widget` command and leave `cli-build` as it is (and remove the `-webpack` suffix from the package name).

**Comment by rishson** [comment]
So the aim of the rename is to have parity between the repo name and the package name on `npm`.
This has already caused some confusion with beta users in the community.

**Comment by mwistrand** [comment]
Yes, I understood that. My question is why not use `cli-build` for both? If building a single widget consists of generating output for a limited set of files, I do not see why that should require an entirely separate package.

**Comment by rishson** [comment]
Ahh - OK. I'll remove that section from the description then, as I think that is a fair point and not connected with this issue.

**Comment by kitsonk** [comment]
All of our CLI commands follow the same format, irrespective of them being tied to a particular technology.  Wouldn't this one be best named `cli-build-project` even though most users would only have use `dojo build` as far as we have plans at the moment?

**Comment by agubler** [comment]
It should at least mirror the current published package name to prevent confusion.

Any discussions on a rename could continue after that :)
