### ISSUE TITLE
Improve the README with the build details

### ISSUE THREAD

**Issue by rishson** [dojo/cli-build-webpack#111]
We should expand the README with:

- what the build does
  - what gets built and where
  - why this is beneficial (size etc)
  - what is part of the build (sourcemaps, js rather than ts, css and why it looks weird)
  - what our widgets look like once built (what they contain etc)
- how the build does it (uses webpack, but light on details)
- cover the various scenarios, build for dev, build for prod..

**Comment by kitsonk** [comment]
We also like need a tutorial that takes you through the process and a blog post about the design ethos of the build process.

I don't know if that is a separate issue or not.

**Comment by kitsonk** [comment]
We also need to help ensure we include enough information to make it easy for someone to perform the process with another tool chain (e.g. like building the modular CSS).

**Comment by dylans** [comment]
> We also like need a tutorial that takes you through the process and a blog post about the design ethos of the build process.

https://github.com/dojo/dojo.io/issues/19 is the issue that will cover the basics, but we should open an additional issue in there for a reference guide around the build process.

**Comment by kitsonk** [comment]
Closing in favour of #189 which is a more complete solution to this issue.
