### ISSUE TITLE
--watch does not always recompile unit tests

### ISSUE THREAD

**Issue by edhager** [dojo/cli-build-webpack#113]
**Bug**

When using --watch, the test source files are not always recompiled when they should.

Steps to reproduce:

1. Create an app: `dojo create --name test`
1. From the app directory, start the build: `dojo build --watch`.
1. Rename `src/App.ts` to `src/App1.ts`.
1. Notice the build watcher recompiles `src/main.ts` and `tests/unit/App.ts` and reports errors.
1. Edit `tests/unit/App.ts` and change the failing import statement to 
`import App from './../../src/App1';`
1. Notice no recompile occurs.
1. Edit `src/main.ts` and fix the import statement.
1. A recompile occurs but it still reports an error in `tests/unit/App.ts` even though the code had been updated.
1. Stop the build watch command and rerun it.
1. No compile errors.

Should the build watch command be compiling the test source files at all?  I am not going to answer that question.  But if there are cases when it is going to compile the files and report errors, then it needs to recompile them when I fix the errors.

**Comment by mwistrand** [comment]
We have the `--withTests` flag for building tests, so as far as I am aware, `--watch` by itself should not concern itself with the test files.

**Comment by mwistrand** [comment]
Actually, @matt-gadd pointed out that `TSLoader` works off the tsconfig, and therefore the whole project, which complicates things a bit.

**Comment by kitsonk** [comment]
Closing in favour of #227
