### ISSUE TITLE
"Building a custom element" logs all errors of tsconfig

### ISSUE THREAD

**Issue by sebilasse** [dojo/cli-build-webpack#131]
When I just want to compile an element, ts goes through all my project root and logs all the errors.
Building the custom element succeeds! But users could be confused by errors caused by e.g. any node module ...

<img width="783" alt="bildschirmfoto 2017-05-07 um 13 20 47" src="https://cloud.githubusercontent.com/assets/750300/25780432/600d52ce-3328-11e7-8c3c-c2637a2e803b.png">

**Comment by sebilasse** [comment]
FYI :

This does not occur if I provide a relative path.
However – I can't use a relative path because the CSS part is not build then ...

**Comment by kitsonk** [comment]
Relative paths should be used.  When you say:

> However – I can't use a relative path because the CSS part is not build then ...

Could you provide more details?  We never seem to have an issue with building the CSS when using relative paths.

**Comment by sebilasse** [comment]
This one is resolved meanwhile since using TS >2.3
In general the underlying problem still exists but is not related with dojo :
Let's say a new version from nodemailer uses typings which require TS with support for string Enums (maybe >2.4). These would not work if the development server uses TS <2.4 and so such errors as above prevent the build.

**Comment by kitsonk** [comment]
Ok, since it is external, I am going to close it.  Anyone else encountering it can use this issue as a reference.
