### ISSUE TITLE
Test failures on Windows

### ISSUE THREAD

**Issue by rorticus** [dojo/cli-build-webpack#183]
Several test failures on Windows,

It looks like most of them are path issues, here is one!

```
× core-load - should add modules with relative IDs when an issuer is the base path (0s)
AssertionError: Module added to ID map.: expected 'var _modules_ = {"@dojo/core/load":{"id":42,"lazy":false}};\n' to equal 'var _modules_ = {"/path/to/module":{"id":1
,"lazy":false},"@dojo/core/load":{"id":42,"lazy":false}};\n'
```

Steps to reproduce (powershell and cmd):

```
npm i 
grunt test
```

**Comment by agubler** [comment]
There is an open PR that has some fixes for windows: https://github.com/dojo/cli-build/pull/176

**Comment by rorticus** [comment]
Looks like this is a dupe of https://github.com/dojo/cli-build-webpack/issues/174
