### ISSUE TITLE
Unable to load modules where filename ends in 'css'

### ISSUE THREAD

**Issue by nicknisi** [dojo/cli-build-webpack#193]
**Bug** 

The loader is unable to load a module where the filename ends in `css`. Examples modules include `css.ts` and `postcss.ts` (`import postcss from './postcss';`).

I believe this may be caused by [this line](https://github.com/dojo/cli-build-webpack/blob/9ba081488f5c0481c5a45f13e11b86fc57bf0039/src/loaders/css-module-dts-loader/loader.ts#L50) because the regex does not look correct, but I haven't yet tested it.

```ts
// line 50 - regex should be /\.css$/ maybe?
if (/.css$/.test(importPath)) {
```

Package Version: 2.0.0-beta2.4 

**Code**

```ts
import postcss from './postcss';
```

**Expected behavior:**

The module should load with no issues.

**Actual behavior:**

 An error occurs (uncaught promise):

```
(node:68060) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: ENOENT: no such file or directory, stat '/Users/nicknisi/code/dojo/editor/src/support/postcss'
```

**Comment by nicknisi** [comment]
Testing in my project, it looks like fixing that regular expression does fix this issue. I can look into creating a PR.

**Comment by kitsonk** [comment]
It seems logical that it would.  Good catch!

**Comment by tomdye** [comment]
@nicknisi bare in mind that any of those `.m.css` files in the built `@dojo/widgets` will be obfuscated and thus I am not sure how useful they will be to you. The only widget css file that is designed to be imported from `@dojo/widgets` is `variables.css`.
