### ISSUE TITLE
Re-architecture of CLI Build

### ISSUE THREAD

**Issue by kitsonk** [dojo/cli-build-webpack#197]
**Enhancement**

The current structure of our build commands is around the tooling and not around the actual application.  @matt-gadd has suggested that we re-architect and restructure the commands to align more to their use.  Specifically we should have:

* A command that builds an application.
* A command that builds a library (maybe a widget library).
* A command that builds a stand alone Web Component.
* Possibly other commands.

We shouldn't _care_ about what the tooling is used to get to that outcome.

**Comment by kitsonk** [comment]
There are a couple issues being addressed under this, so converting to an epic and linking in other issues.

**Comment by agubler** [comment]
The re-architecture is complete with `dojo/cli-build-app` and `dojo/cli-build-widget`, further enhancements or issues are tracked in their respective issues.
