### ISSUE TITLE
pass host to webpack to enable development over the network

### ISSUE THREAD

**Issue by bwakkie** [dojo/cli-build-webpack#215]
As discussed on gitter hereby my feature request to be able to pass the host flag to the webpack dev server to enable development over the 'local' network.
eg. something in the direction of: `dojo build -w --host 192.168.0.0`

**Comment by agubler** [comment]
Moving this to cli-build-app, it maybe that there is already an issue that covers it in which case we can close later.

**Comment by agubler** [comment]
Issue moved to [dojo/cli-build-app #106](https://github.com/dojo/cli-build-app/issues/106) via [**ZenHub**](https://www.zenhub.com/)
