### ISSUE TITLE
Should 'dojo build' clear the dist folder?

### ISSUE THREAD

**Issue by umaar** [dojo/cli-build-webpack#228]
I found this when following along with this Dojo 2 tutorial:

https://dojo.io/tutorials/006_deploying_to_production/#1

Step 1: "Run the dojo build command." I noticed when I run dojo build multiple times, it does not clear the dist folder each time. Not wiping the workspace I feel is sometimes a source of bugs. Also I notice individual CSS files are copied over (006_deploying_to_production/initial/biz-e-corp/dist/styles) into the dist folder and it is not clear why - this could also be a potential source of bugs.

**Comment by kitsonk** [comment]
It should do a clean.
