### ISSUE TITLE
Possibility to change webpack dev-server configuration

### ISSUE THREAD

**Issue by evra** [dojo/cli-build-webpack#239]
**Enhancement** 

Package Version: 0.2.1-pre

It would be very helpfull to have a possibility to change default webpack dev server configuration - https://github.com/webpack/webpack-dev-server

One of the usecases would be a possibility to configure REST api proxy parameters (see for example: https://github.com/webpack/webpack-dev-server/blob/master/examples/proxy-simple/webpack.config.js)  or use the history api.

**Comment by kitsonk** [comment]
Thanks for the feedback!

Agreed that it might be a good thing to provide some level of access to _control_ the development server to make it easier to fit wider use cases.

We are currently re-writing the build tool for Beta 5.

**Comment by agubler** [comment]
This has been moved to cli-build-app
