### ISSUE TITLE
Deprecation warning with current custom element template

### ISSUE THREAD

**Issue by mwistrand** [dojo/cli-build-webpack#241]
**Bug**

When building custom elements, the `<link href="<%= htmlWebpackPlugin.files.css[css] %>" rel="stylesheet">` output to the custom element import triggers the following warning in Chrome:

>[Deprecation] Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.

The link referenced in the warning suggests programmatically reassigning the `<link>` for the widget CSS to the master `document`, but that of course assumes the `href` is correct in both contexts.

Package Version: 0.1.0

**Comment by agubler** [comment]
Custom Elements no longer use HTML Imports with `cli-build-widget`
