### ISSUE TITLE
CSS Source Maps

### ISSUE THREAD

**Issue by kitsonk** [dojo/cli-build-webpack#243]
**Bug**

It appears since we moved to webpack 3, source maps for CSS does not appear to be working any longer.  When inspecting a class name, you end up being directed to the "bundled" CSS instead of the source CSS, though the source CSS does appear to be available in the webpack bundle.

**Comment by agubler** [comment]
CSS source maps are working as expected in `cli-build-app` and `cli-build-webpack` has been deprecated.
