### ISSUE TITLE
CLI Build Widget

### ISSUE THREAD

**Issue by kitsonk** [dojo/cli-build-webpack#257]
**Enhancement**

With the changes that will be delivered with `cli-build-app` (see #197) there is an area of functionality that is not covered by the build of an "app".  This is the functionality to create a redistributable of a widget or a set of widgets for consumption in other libraries.

This epic is designed to track the tasks related to this feature.  At a minimum, the use cases that need to be addressed are:

* The ability to "build" a widget or set of widgets, so that it can be easily integrated and imported into other applications, including the appropriate TypeScript typings.
* The ability to "build" a widget or set of widgets that can be used as custom elements/Web Components without further build processing by a consumer.

**Comment by agubler** [comment]
This has been covered by the `cli-build-widget` command - currently supports a target of a custom element with a future enhancement to build individual native dojo 2 widgets.
