### ISSUE TITLE
Assume `src/` directory prefix in message bundle paths.

### ISSUE THREAD

**Issue by mwistrand** [dojo/cli-build-webpack#42]
**Enhancement**

When building an application with localized message bundles, the `bundlePath` specified by the default bundle must be the full path from the current working directory. However, since it is assumed that all application source will be included in the `src/` directory, it would be nice if that root directory were assumed by the build. That would allow message bundles to specify their bundle paths without that root directory. For example, a bundle at `src/nls/common.ts` could specify its `bundlePath` as just `nls/common` instead of as `src/nls/common`.

**Comment by mwistrand** [comment]
Now that I take a closer look at this, it appears to be more complicated than I initially anticipated. `@dojo/i18n/i18n` loads locale-specific bundles through `@dojo/core/load/webpack`, which matches the bundle path to a webpack-specific mid. For example, `'src/nls/common': { id: 178 }`.

To allow both `'src/nls/common'` and `'nls/common'` to be loaded, we would either need an additional mapping in the internal webpack `__modules__` map, or `@dojo/core/load/webpack` would need to be updated to prepend `src/` to unfound modules. Neither one of these approaches is entirely bulletproof, so perhaps it would be best to continue requiring that `bundlePath`s are set from the root?

**Comment by kitsonk** [comment]
What sort of action needs to occur on this?  We should either decide something or close this issue down.

**Comment by mwistrand** [comment]
We are currently modifying how translations are injected into the bundle, and requiring the full base path is not that problematic, so I'm 100% fine tabling this for the time being.
