### ISSUE TITLE
Enhance `build` to produce layer files

### ISSUE THREAD

**Issue by dylans** [dojo/cli-build-webpack#59]
@rishson commented on [Mon Oct 03 2016](https://github.com/dojo/cli/issues/59)

A lá dojo1.

---

@kitsonk commented on [Mon Oct 03 2016](https://github.com/dojo/cli/issues/59#issuecomment-251121019)

Refs dojo/meta#34

---

@matt-gadd commented on [Fri Oct 14 2016](https://github.com/dojo/cli/issues/59#issuecomment-253750661)

@rishson can we state the problem rather than dictating a solution. there are a variety of ways we will want to make our apps performant at build time.

---

@rishson commented on [Fri Oct 14 2016](https://github.com/dojo/cli/issues/59#issuecomment-253754490)

@matt-gadd fair point. I'll create a 'performance' epic on `cli` to start discussion on what we can do to create well behaved, performant apps.

---

@kitsonk commented on [Fri Oct 14 2016](https://github.com/dojo/cli/issues/59#issuecomment-253782806)

So are we keeping this open then?

As far as a user story, I would say this one is one like this:

> In complex web applications with multiple views, where certain views were in order to have a functional application, not all modules are needed to be loaded upon page load, and groups of modules, with any additional dependencies not already loaded, can be loaded efficiently.
> 
> In Dojo 1, this was accomplished by allowing the developer to group modules into logical sets which then allowed the developer to specify "layers" to allow efficient incremental loading of code and other resources as triggered by certain actions in the application.

---

@agubler commented on [Fri Oct 14 2016](https://github.com/dojo/cli/issues/59#issuecomment-253784828)

I think that this would certainly warrant being kept open as a story, maybe under the wider performance epic.

---

@agubler commented on [Wed Feb 01 2017](https://github.com/dojo/cli/issues/59#issuecomment-276657246)

This should probably be moved to [cli build](https://github.com/dojo/cli-build), but with more details of the problem

**Comment by dylans** [comment]
The idea of build layers is to create layers that can be optimized, rather than 1 large JS file. Some use cases:

* Initial shared lib, used by many apps
* Each other app depends on shared layer, and then has its own layer

* Caching, e.g. things that rarely changes in one layer, things that change regularly in another layer

* Feature driven, e.g. common and cheap features in one layer, expensive features in separate layers (e.g. in an email client, moving chat and calendar features to separate layers if most users focus primarily on email)

Some of these use cases don't matter as much in HTTP/2, but still worth considering what we want to do.

**Comment by kitsonk** [comment]
Code splitting is important, but I thin we need to think about this more and get some more real world use cases under our belt before we make this super easy for an end user.  Right now, if someone is really ready for good code splitting, they should consider using Webpack and a build toolchain as a standalone...

**Comment by kitsonk** [comment]
References #189

Also, the build tool does allow chunks to be built at the moment, though that process isn't documented.

**Comment by agubler** [comment]
Code splitting is included in `cli-build-app`, closing.
