### ISSUE TITLE
The bundle analyser report only supports a single bundle

### ISSUE THREAD

**Issue by agubler** [dojo/cli-build-webpack#99]
**Bug** 

cli-build now supports auto and manually defined bundles, but the bundle analyser only supports a single bundle outputting the last created bundle only.

The analyser should support multiple bundles and create a report/reports that reflect them.

**Comment by kitsonk** [comment]
Did this get fixed recently or was there more to do?

**Comment by matt-gadd** [comment]
@kitsonk i think it's now resolved downstream by https://github.com/bitpshr/webpack-bundle-analyzer, but we need to bump the version in the `package.json` here
